version: '3'

services:
    front:
        build: ./front
        restart: always
        ports:
            - "3000:3000"
        container_name: front_phux
    back:
        restart: always
        build: ./back
        command: yarn start
        ports:
            - "8000:8000"
        container_name: back_phux
        networks:
            - db
        environment:
            - API_PORT=8000
            - DB_USER=ephuxpoang
            - DB_PASSWORD=ephuxpoang
            - DB_NAME=phuxdb
            - DB_HOST=db
            - SECRET=kossusmakarbasturmetalkopp2021
        restart: always
        depends_on:
            - db
    db:
        container_name: phux-db
        image: postgres:9.6.5-alpine
        ports:
            - "5432:5432" # For being able to connect from host to container database
        networks:
            - db
        environment:
            - POSTGRES_USER=ephuxpoang
            - POSTGRES_PASSWORD=ephuxpoang
            - POSTGRES_DB=phuxdb
            - POSTGRES_HOST=phuxdb
            - POSTGRES_PORT=5432
        volumes:
            - db-data:/var/lib/postgresql/data/
        restart: always

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge