version: '3'

services:
    back:
        restart: always
        build: .
        ports:
            - "8000:8000"
        container_name: back_phux
        networks:
            - db
            # Add the reverse proxy network here
        environment:
            - API_PORT=8000
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=phuxdb
            - DB_HOST=db
            - SECRET=kossusmakarbasturmetalkopp2021
        depends_on:
            - db
    db:
        container_name: phux-db
        image: postgres:9.6.5-alpine
        ports:
            - "5432:5432" # For being able to connect from host to container database
        networks:
            - db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=phuxdb
            - POSTGRES_HOST=phuxdb
            - POSTGRES_PORT=5432
        volumes:
            - ./db-data:/var/lib/postgresql/data/
        restart: always

volumes:
  db-data:
    driver: local

networks:
  db:
    driver: bridge