POST http://localhost:8000/api/events
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6MiwiaWF0IjoxNjI2MTc2MjQ5fQ.RxdtSz5rVkH38aHU_ZKw7eQTFxwZ0TGzMFNeOLHkQVU

{ 
    "name": "NaMö",
    "description": "Nationsmöte",
    "startTime": "01-01-2021",
    "endTime": "02-01-2021",
    "points": "10",
    "userLimit": 200,
    "categoryId": 1,
    "mandatory": true
}

###