POST http://localhost:8000/api/events
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6NSwiaWF0IjoxNjI5ODAyMTE5fQ.s2uyZeFTMpvA6YOjtud0FLWLVX4hy0Bmh_KSjpfMc80

{ 
    "name": "NaMö",
    "description": "Nationsmöte",
    "startTime": "01-01-2021",
    "endTime": "02-01-2021",
    "points": "10",
    "userLimit": 200,
    "categoryId": 1,
    "mandatory": true
}

###

POST http://localhost:8000/api/events
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6NSwiaWF0IjoxNjI5ODAyMTE5fQ.s2uyZeFTMpvA6YOjtud0FLWLVX4hy0Bmh_KSjpfMc80

{ 
    "name": "Fest1",
    "description": "Bästa festen (utom fö phuxk)",
    "startTime": "01-01-2021",
    "endTime": "02-01-2021",
    "points": "100",
    "userLimit": 50,
    "categoryId": 2,
    "mandatory": false
}

###

POST http://localhost:8000/api/events
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6MiwiaWF0IjoxNjI2MTc2MjQ5fQ.RxdtSz5rVkH38aHU_ZKw7eQTFxwZ0TGzMFNeOLHkQVU

{ 
    "name": "Julphesten",
    "description": "Människor e nog satins fulla här",
    "startTime": "01-01-2021",
    "endTime": "02-01-2021",
    "points": "-10",
    "userLimit": 150,
    "categoryId": 2,
    "mandatory": false
}

###