POST http://localhost:8000/api/categories
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6MiwiaWF0IjoxNjMzNzE0Nzc2fQ.H0dACf2ooyMw-ezaSgjNM64VjQb7qywYnNPlqqk2nbc

{ 
    "name": "Obligatoriska",
    "description": "Dessa poäng är alla obligatoriska att göra "
}

###

POST http://localhost:8000/api/categories
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6MiwiaWF0IjoxNjMzNzE0Nzc2fQ.H0dACf2ooyMw-ezaSgjNM64VjQb7qywYnNPlqqk2nbc

{ 
    "name": "Fest",
    "description": "Helt jävla festliga poäng",
    "minPoints": 100
}

###