POST http://localhost:8000/categories
Content-Type: application/json

{ 
    "name": "Obligatoriska",
    "description": "Dessa poäng är alla obligatoriska att göra "
}

###

POST http://localhost:8000/categories
Content-Type: application/json

{ 
    "name": "Fest",
    "description": "Helt jävla festliga poäng",
    "minPoints": 100
}

###