PUT http://localhost:8000/api/categories/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6NSwiaWF0IjoxNjI5ODAyMTE5fQ.s2uyZeFTMpvA6YOjtud0FLWLVX4hy0Bmh_KSjpfMc80

{ 
    "name": "Obligatoriska",
    "description": "Dessa poäng är alla obligatoriska att göra",
    "minPoints": 10
}
###