POST http://localhost:8000/api/users
Content-Type: application/json

{ 
    "role": "BASIC",
    "email": "john.doe@aalto.fi",
    "password": "hunter2",
    "firstName": "John",
    "lastName": "Doe",
    "fieldOfStudy": "Raksa",
    "events": [],
    "capWithTF": true
}

###
POST http://localhost:8000/api/users
Content-Type: application/json

{ 
    "role": "ADMIN",
    "email": "phuxivator@tf.fi",
    "password": "naritet4ever",
    "firstName": "Phux",
    "lastName": "Ivator",
    "fieldOfStudy": "TF",
    "events": [],
    "capWithTF": false
}

###
POST http://localhost:8000/api/users
Content-Type: application/json

{ 
    "role": "BASIC",
    "email": "jane.doe@aalto.fi",
    "password": "hunter2",
    "firstName": "Jane",
    "lastName": "Doe",
    "fieldOfStudy": "Raksa",
    "events": [],
    "capWithTF": true
}