POST http://localhost:8000/users
Content-Type: application/json

{ 
    "role": "basic",
    "username": "john.doe",
    "password": "hunter2",
    "firstName": "John",
    "lastName": "Doe",
    "fieldOfStudy": "Raksa",
    "events": [],
    "capWithTF": true
}

###
POST http://localhost:8000/users
Content-Type: application/json

{ 
    "role": "admin",
    "username": "Phuxivator",
    "password": "naritet4ever",
    "firstName": "Phux",
    "lastName": "Ivator",
    "fieldOfStudy": "TF",
    "events": [],
    "capWithTF": false
}