POST http://localhost:8000/api/users/4/done_events/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBodXhpdmF0b3JAdGYuZmkiLCJpZCI6MiwiaWF0IjoxNjMzNzE0Nzc2fQ.H0dACf2ooyMw-ezaSgjNM64VjQb7qywYnNPlqqk2nbc

###

POST http://localhost:8000/api/users/4/done_events/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGFhbHRvLmZpIiwiaWQiOjEsImlhdCI6MTYyNjE3NzAyOH0.yIcdg-BJAJPZsIvh7KKcnZqo7jG6MF3dldxNgQDxt_c